# Generated by Django 3.2.5 on 2021-07-17 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Attendance Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Attendance Time'),
        ),
        migrations.AlterField(
            model_name='link',
            name='token',
            field=models.CharField(default='Mn8HLc3vxRONjdXbGlZOePUem', max_length=100, verbose_name='Key'),
        ),
    ]
