# Generated by Django 3.2.5 on 2021-07-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210717_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='token',
            field=models.CharField(default='0bJmKos1qfXMQA9OEyI2r9Ty0', max_length=100, verbose_name='Key'),
        ),
    ]
