# Generated by Django 3.2.5 on 2021-07-17 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_link_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='link',
            field=models.ForeignKey(default='Deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.link'),
        ),
        migrations.AlterField(
            model_name='link',
            name='token',
            field=models.CharField(default='iir0MrWM6stPcgkMbdcseFvdb', max_length=100, verbose_name='Key'),
        ),
    ]
