# Generated by Django 3.2.5 on 2021-07-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_link_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='code',
            field=models.IntegerField(default=1, unique=True, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='token',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Key'),
        ),
    ]
