# Generated by Django 3.2.5 on 2021-07-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210718_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, to='dashboard.Student', verbose_name='Students In This Class'),
        ),
    ]
