# Generated by Django 3.2.5 on 2021-07-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_class_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='code',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='link',
            name='token',
            field=models.CharField(blank=True, max_length=1024, unique=True, verbose_name='Key'),
        ),
    ]
