# Generated by Django 3.2.5 on 2021-07-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_student_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='class_name',
        ),
    ]
