# Generated by Django 3.2.5 on 2021-07-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_attendance_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(verbose_name='Attendance Date'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_time',
            field=models.TimeField(verbose_name='Attendance Time'),
        ),
    ]
