# Generated by Django 3.2.5 on 2021-07-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_student_student'),
        ('home', '0003_profile_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.PositiveIntegerField(default=5, verbose_name='Age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default='jimam', max_length=10, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default='tamimi', max_length=10, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='number',
            field=models.CharField(default=43454, max_length=30, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
