# Generated by Django 3.2.5 on 2021-07-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_myuser_addtional_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_completed',
        ),
    ]
