# Generated by Django 3.2.5 on 2021-07-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_is_verified_myuser_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='in_draft',
            field=models.BooleanField(default=False),
        ),
    ]
